[workspace]
resolver = "2"
default-members = [ "plrust", "guest_template" ]
members = [
    "plrust",
    "guest_template",
    "components/interface"
]

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
