[workspace]
resolver = "2"
members = [
    "plrust",
    "trusted-pgx",
]

[profile.dev.build-override]
opt-level = 3

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
