[package]
name = "doesitwork"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plrust_plugins = {path = "../plugin"}
libc = "0.2"
serde = "1"
