[package]
name = "plrust"
version = "0.0.0"
authors = ["ZomboDB, LLC <zombodb@gmail.com>"]
edition = "2021"
license = "PostgreSQL Open Source License"
description = "A Rust procedural language for PostgreSQL"
homepage = "https://github.com/zombodb/plrust/"
repository = "https://github.com/zombodb/plrust/"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg14"]
pg10 = ["pgx/pg10", "pgx-tests/pg10"]
pg11 = ["pgx/pg11", "pgx-tests/pg11"]
pg12 = ["pgx/pg12", "pgx-tests/pg12"]
pg13 = ["pgx/pg13", "pgx-tests/pg13"]
pg14 = ["pgx/pg14", "pgx-tests/pg14"]
pg_test = []
# Be accomodating to sandboxed builds with no network.
sandboxed = []

[dependencies]
bincode = "1"
pgx = "0.4.2"
wit-bindgen-wasmtime = { git = "https://github.com/bytecodealliance/wit-bindgen.git", rev = "bb33644b4fd21ecf43761f63c472cdfffe57e300", features = ["tracing"] }
wasmtime = "0.35"
wasmtime-wasi = "0.35"
wasi-common = "0.35"
syn = "1"
proc-macro2 = "1"
prettyplease = "0.1"
cargo_metadata = "0.14.2"
thiserror = "1.0"
eyre = "0.6"
color-eyre = "0.6"
atty = "0.2"
include_dir = "0.7"
cargo_toml = "0.11"
toml = "0.5"

[dev-dependencies]
pgx-tests = "0.4.2"
tempdir = "0.3.7"
once_cell = "1.7.2"
toml = "0.5.8"
